### ISSUE TITLE
遇到了train的问题

### ISSUE THREAD

**Issue by gittigxuy** [syfafterzy/SVDNet-for-Pedestrian-Retrieval#1]
在这个train_basemodel.sh里面
BasemodelPath=
Train_Data_Path=~/market1501/caffenet_img_train_lmdb
Val_Data_Path=~/market1501/caffenet_img_test_lmdb

这三行是怎么定义的呢？那个market1501应该改成什么？caffenet_img_train_lmdb应该改为什么呢？我没有找到这个文件。
BasemodelPath这个应该填写什么呢？

**Comment by ghost** [comment]
感谢您的关注！

首先，BasemodelPath是预训练的模型。也就是您要finetuning的基础模型，您需要事先下载好pretrained model，放置好后，添加您的路径。Please define the path of imagenet pre-trained CaffeNet or ResNet-50。

其次，LMDB是训练和交叉验证数据的格式，需要事先制作好，您可以查看caffe官方对训练数据格式的说明： http://caffe.berkeleyvision.org/tutorial/data.html 。需要您事先制作好LMDB文件，您可以查看caffe官方给出的examples，或者参考这里：http://www.cnblogs.com/dupuleng/articles/4370236.html。

祝您实验顺利！

**Comment by gittigxuy** [comment]
你说的pretrained model，是之前放百度网盘链接的linear_caffemodel的这个文件夹吗？制作LMDB文件需要数据集啊，数据集是我自己的数据集还是你们给提供数据集呢？如果是用我自己的数据集的话能不能用行人的图片，这种数据集呢？

**Comment by ghost** [comment]
您好，Pre-trained model是指在ImgeNet数据集合上训练好的模型，我们在Pre-trained model基础上用自己的数据Finetuning。论文里面采用的是CaffeNet和ResNet-50，您可以自己在caffe官方下载。或者查看这里：https://github.com/zhunzhong07/IDE-baseline-Market-1501。

论文里面的数据集合是Market-1501 dataset : http://liangzheng.com.cn/Project/project_reid.html
和DukeMTMC-ReID dataset：https://github.com/layumi/DukeMTMC-reID_evaluation

您可以根据自己的需要，按照原有的格式整理好数据之后训练。

**Comment by gittigxuy** [comment]
1）那你提供的1024d_linear.caffemodel是干嘛用的呢？既然你给我另外一些caffemodel的下载地址，我的理解应该是将你提供的1024d_linear.caffemodel的路径BasemodelPath放到这个参数后面进行训练。
2）然后我下载了Market-1501 dataset，这些图片的话我就自己划分train set 和val set呗，然后制作成train lmdb 以及val lmdb文件，这样就应该可以了吧？

**Comment by ghost** [comment]
请您仔细阅读SVDNet这个论文。为了方便使用，我们提供了SVDNet的basemodel。这样就可以在basemodel的基础上，进一步采用train_RRI.sh来训练SVDNet。

您提的问题是train_basemodel.sh里面，训练train_basemodel的问题，您如果需要自己训练自己训练SVDNet的basemodel，相关上面已经说的很详细了。具体实验的细节和参数，论文和代码也写清楚了。

Market1501和Duke数据集合的详细介绍和数据集合划分，请查看 Market-1501 dataset : http://liangzheng.com.cn/Project/project_reid.html
和DukeMTMC-ReID dataset：https://github.com/layumi/DukeMTMC-reID_evaluation

至于基础的Caffe训练和使用，请参考caffe官网相关教程。谢谢。
