### ISSUE TITLE
About solver.prototxt

### ISSUE THREAD

**Issue by rainsoulsrx** [syfafterzy/SVDNet-for-Pedestrian-Retrieval#3]
I notice that base_lr is set to be 0.001 in all solver_restraint.prototxt, normally, base_lr should change smaller as the training process goes on, but the given code keep on using 0.001. will it converg very well in the end?

**Comment by ghost** [comment]
Thanks for Ur question.

Actually, the base_lr do change smaller as the training process goes on.

Please see details at:
https://github.com/syfafterzy/SVDNet-for-Pedestrian-Retrieval/blob/master/SVDNet/resnet/base_lr.txt.

**Comment by rainsoulsrx** [comment]
Thx, but the caffenet solver_restraint.prototxt, base_lr: 0.001, lr_policy: "step", stepsize: 2000, max_iter: 2000, that is to say, the lr keeps to be 0.01 during the restraint stage, right?

**Comment by syfafterzy** [comment]
Yes, you are right. For CaffeNet, we only fine-tune the network to good convergence  during the last RRI, to reduce training time.

**Comment by rainsoulsrx** [comment]
Thank you~~
